import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import DataProvider from "./_components/DataProvider";
import Link from "next/link";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <header className="bg-blue-500 text-white p-4 text-center">
          <h1 className="text-2xl font-bold mb-2 bg-white text-blue-600 inline-block px-4 py-1 rounded">Simple App</h1>
          <nav className="mt-2 space-x-4">
            <Link href="/" className="hover:underline">Home</Link>
            <Link href="/input" className="hover:underline">Input</Link>
            <Link href="/show" className="hover:underline">Show</Link>
          </nav>
        </header>
        <hr />
        <DataProvider>
           {children}
        </DataProvider>
      </body>
    </html>
  );
}
