

export const metadata = {
  title: 'Addition',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
 
  
  return (

   
    <html lang="en">
      <body>
        <h1>Sum</h1>
    
        <hr />
        {children}
       
        </body>
    </html>
  )
}
